### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by yormi** [sindresorhus/grunt-sass#207]
Hey folks !

Maybe I'm missing something but it looks like I have some problem... If you need more info, just ask :)

Thanks in advance for any help !

>Fatal error: undefined is not a function
TypeError: undefined is not a function
    at getOptions (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:137:73)
    at Object.module.exports.render (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:198:13)
    at Object.<anonymous> (/home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/tasks/sass.js:23:9)
    at Immediate.immediate._onImmediate (timers.js:409:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by sindresorhus** [comment]
That's coming from node-sass:

> /home/guillaume/Documents/LiU/TDDD27/slackportal/frontend/node_modules/grunt-sass/node_modules/**node-sass**/lib/index.js:137:73

https://github.com/sass/node-sass/issues
